steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$COMMIT_SHA'
      - '--build-arg=BASE_IMAGE=$_BASE_IMAGE'
      - '--build-arg=BASE_IMAGE_RUN=$_BASE_IMAGE_RUN'
      - '--build-arg=CLASS_NAME=$_CLASS_NAME'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$COMMIT_SHA' ]
  # Deploy the built image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$REPO_NAME'
      - '--image=$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--quiet'
substitutions:
  _REPOSITORY_HOSTNAME: europe-west1-docker.pkg.dev
  _BASE_IMAGE: ghcr.io/graalvm/native-image-community:17-ol9
  _BASE_IMAGE_RUN: ubuntu:latest
  _CLASS_NAME: biz.turnonline.ecosystem.skeleton.Application
