steps:
  - name: 'ghcr.io/graalvm/graalvm-ce:ol9-java17-22.3.2'
    entrypoint: /bin/bash
    args: [ '-c','gu install native-image' ]
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'package'
      - '-Dpackaging=native-image'
  # Build the project and push container image by maven JIB plugin
  - name: 'gcr.io/cloud-builders/mvn'
    args:
      - 'compile'
      - 'jib:build'
      - '-Dimage=$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$COMMIT_SHA'
  # Deploy the built image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$REPO_NAME'
      - '--image=$_REPOSITORY_HOSTNAME/$PROJECT_ID/docker-images/$REPO_NAME:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--quiet'
substitutions:
  _REPOSITORY_HOSTNAME: europe-west1-docker.pkg.dev
